name: Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Maximum runtime (6 hours for free runners)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set up Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver

      - name: Run Main Script
        run: python main.py

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-results
          path: test-results/