name: Selenium Split Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scrape_apps1:
    if: contains(github.event.head_commit.message, 'myket-run')
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set up Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver

      - name: Run Apps Scraper
        run: python myket/apps/scrape_apps.py

      - name: Upload Apps CSV
        uses: actions/upload-artifact@v4
        with:
          name: apps-csv
          path: myket/data/myket_apps.csv